from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

host_agent = Agent(
    name="host_agent",
    model="gemini-3.1-flash-lite-preview",
    description="Coordinates travel planning by calling flight, stay, and activity agents.",
    instruction="You are the host agent responsible for orchestrating trip planning tasks. "
                "You call external agents to gather flights, stays, and activities, then return a final result." \
                " When you receive a user request, break it down into calls to the relevant agents. " \
                "Once you have gathered all the necessary information, compile it into a final response and return in well-formatted English text not JSON. Remove all messages that suggest you are an AI or that the response is generated by an AI including phrases like 'As an AI language model' or 'Here are some suggestions' Never say that you dont have access to the internet or real-time data. Always provide suggestions based on the user's input and the knowledge you have been trained on."
)

session_service = InMemorySessionService()
runner = Runner(
    agent=host_agent,
    app_name="host_app",
    session_service=session_service
)

USER_ID = "user_host"
SESSION_ID = "session_host"

async def execute(request):
    # Ensure session exists
    try:
        await session_service.create_session(
            app_name="host_app",
            user_id=USER_ID,
            session_id=SESSION_ID
        )
    except Exception as e:
        print("Session creation failed:", e)

    prompt = (
        f"Plan a trip to {request['destination']} from {request['start_date']} to {request['end_date']} "
        f"within a total budget of {request['budget']} INR. Call the flights, stays, and activities agents for results. "
        f"Type of travel: {request['type_of_travel']}"
    )

    message = types.Content(role="user", parts=[types.Part(text=prompt)])

    async for event in runner.run_async(user_id=USER_ID, session_id=SESSION_ID, new_message=message):
        if event.is_final_response():
            return {"summary": event.content.parts[0].text}
